# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Plugin

on:
  push:
    tags:
      - "*"

jobs:
  release:
    environment: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup with Gradle
        uses: gradle/gradle-build-action@v2.6.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check
        run: xvfb-run --auto-servernum ./gradlew check -Pversion="${{ github.ref_name }}"
        env:
          JAVA_TOOL_OPTIONS: "-Dprism.verbose=true -Dprism.order=sw"

      - name: Configure GPG Key
        run: |
          echo -n "${{ secrets.SIGNING_KEY }}" | base64 --decode > $HOME/secring.gpg

      - name: Publish
        run: xvfb-run --auto-servernum ./gradlew publishPlugins -Pversion="${{ github.ref_name }}" -Psigning.secretKeyRingFile="$HOME/secring.gpg" -Psigning.password="${{ secrets.SIGNING_KEY_PASSWORD }}" -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}" -Pgradle.publish.key="${{ secrets.GRADLE_KEY }}" -Pgradle.publish.secret="${{ secrets.GRADLE_SECRET }}"
        env:
          JAVA_TOOL_OPTIONS: "-Dprism.verbose=true -Dprism.order=sw"